spring:
  datasource:
    url: jdbc:mysql://192.168.1.12:3306/bdnutriapp
    username: mysqluser
    password: mysqlpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name: data-extractor-api
  devtools:
    restart:
      enabled: false

server:
  port: 8080

# Configuración para la conexión Docker
logging:
  level:
    org.springframework: INFO

docker:
  network: mysql_network